### ISSUE TITLE
Unable to enter the Docker container

### ISSUE THREAD

**Issue by CharlieJoller** [urppeia/docker_bio_609_610#5]
Even though it does show up in Docker I do not I seem to be able to build the Docker image correctly as I cannot enter the image using the command: ./login_student.sh
Error response from daemon: No such container: biodocker
Error: failed to start containers: biodocker
Error: No such container: biodocker

This is where I am at in my Terminal: 
PMI-funneliformis:docker_bio_609_610_634 charlottejoller$ ls
Dockerfile		data			run_student.sh
README.md		login_student.sh	win_login_student.sh
build.sh		run_root.sh

**Comment by dktanwar** [comment]
https://github.com/urppeia/docker_bio_609_610_634#build-the-docker-container

You would have to first build the image using build.sh file.
________________________________
From: CharlieJoller ***@***.***>
Sent: Monday, October 31, 2022 7:14:01 AM
To: urppeia/docker_bio_609_610_634 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [urppeia/docker_bio_609_610_634] Unable to enter the Docker container (Issue #5)


Even though it does show up in Docker I do not I seem to be able to build the Docker image correctly as I cannot enter the image using the command: ./login_student.sh
Error response from daemon: No such container: biodocker
Error: failed to start containers: biodocker
Error: No such container: biodocker

This is where I am at in my Terminal:
PMI-funneliformis:docker_bio_609_610_634 charlottejoller$ ls
Dockerfile data run_student.sh
README.md login_student.sh win_login_student.sh
build.sh run_root.sh
